model_deployments:
  - name: vllm/gpt-oss-20b-local
    model_name: openai/gpt-oss-20b
    tokenizer_name: openai/o200k_harmony
    max_sequence_length: 32768
    client_spec:
      class_name: "helm.clients.vllm_client.VLLMChatClient"
      args:
        base_url: "http://localhost:8000/v1"
        vllm_model_name: "openai/gpt-oss-20b"
